# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Merve Arslan
tagline:             
description:         
url:                 http://mervearslan.me
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Merve Arslan
  url:               https://twitter.com/mrvearslnn_
  email:             mrvearsln@gmail.com

# Custom vars
version:             1.0.0
